site_name: glhelp
site_description: "Biblioteka pomocnicza OpenGL."

docs_dir: docs_src

theme:
  name: material

nav:
  - "Main Page": "index.md"
  - "API Docs": "api/index.html"

exclude_docs: |
  api/
